on:
  push:
    paths:
      - src
      - Cargo.*
      - Dockerfile
  workflow_dispatch:

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build
        run: cargo build
